# Generated by Django 5.0 on 2023-12-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meds',
            fields=[
                ('medId', models.IntegerField(default=1530, primary_key=True, serialize=False)),
                ('medName', models.CharField(max_length=100)),
                ('genericName', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('ageGroup', models.CharField(choices=[('Kids', 'Kids'), ('Adults', 'Adults')], max_length=20)),
                ('formulation', models.CharField(max_length=255, null=True)),
                ('netContent', models.CharField(max_length=255, null=True)),
                ('indication', models.CharField(max_length=255)),
                ('sideEffects', models.CharField(max_length=255)),
                ('availability', models.BooleanField(default=True)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
