# Generated by Django 5.0 on 2023-12-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_meds_medtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meds',
            name='medType',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Liquid', 'Liquid')], max_length=100),
        ),
    ]
