# Generated by Django 5.0 on 2023-12-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_meds_medtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meds',
            name='medId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
