# Generated by Django 5.0 on 2023-12-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_meds_medid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meds',
            name='medId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
